# Generated by Django 2.2.5 on 2019-09-18 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
