# Generated by Django 2.2.5 on 2019-09-18 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_room_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['floor'], 'verbose_name': 'Quarto', 'verbose_name_plural': 'Quartos'},
        ),
        migrations.AlterField(
            model_name='room',
            name='floor',
            field=models.IntegerField(verbose_name='Piso'),
        ),
        migrations.AlterField(
            model_name='room',
            name='number',
            field=models.IntegerField(verbose_name='Número'),
        ),
    ]
