# Generated by Django 2.2.5 on 2019-09-18 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_auto_20190918_0657'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('number', 'floor')},
        ),
    ]
