# Generated by Django 2.2.5 on 2019-09-18 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_auto_20190918_0933'),
        ('rooms', '0009_auto_20190918_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='floor',
            field=models.IntegerField(default=1, verbose_name='Piso'),
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('floor', 'hotel')},
        ),
    ]
