# Generated by Django 2.2.5 on 2019-09-18 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0011_auto_20190918_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='description',
            field=models.CharField(max_length=100, null=True, verbose_name='Descrição'),
        ),
    ]
