# Generated by Django 2.2.5 on 2019-09-18 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotel',
            options={'ordering': ['name'], 'verbose_name': 'Hotel', 'verbose_name_plural': 'Hotéis'},
        ),
    ]
