# Generated by Django 2.2.5 on 2019-09-18 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_auto_20190917_2304'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hotel',
            unique_together={('name', 'city')},
        ),
    ]
